### ISSUE TITLE
Sujerencias

### ISSUE THREAD

**Issue by vanessamarely** [carlosrojaso/angular-week-conference-app#1]
**Speakers** 

- Podrias eliminar el texto 'Sobre ...'

- Podrias colocar el 'Tweet' y el 'share' en una sola fila en el responsive

![screen shot 2018-04-22 at 4 03 26 pm](https://user-images.githubusercontent.com/4331491/39099906-894c5d96-4647-11e8-983e-5e6e839015e5.png)
![screen shot 2018-04-22 at 4 03 33 pm](https://user-images.githubusercontent.com/4331491/39099907-8964fd38-4647-11e8-9acf-1ec8fe7a476a.png)
 

- Podrias ocultar el link de twitter para los speakers que no lo tienen.

- Cuando la aplicacion inicia aparece un color verde corporativo de fondo con el icono de la angular week, podrias remover el fondo de esa seccion, dejarlo blanco para que el logo resalte.

**Comment by carlosrojaso** [comment]
done. missing minor changes.
